id: P006605
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:09:54.990913
source_metadata:
  id: bdr:W1KG24744
  title: འདུལ་བའི་དོགས་དཔྱོད།
  author: ''
  volumes:
    cfbb0218877844fbbcdf60bd0719a533:
      image_group_id: I1KG24746
      title: ''
      volume_number: 1
      total_pages: 275
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
