id: I72AD2491
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:08:57+00:00'
last_modified: '2022-06-08T05:34:46.714190+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24744
  title: འདུལ་བའི་དོགས་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    96C2:
      image_group_id: I1KG24746
      title: ''
      total_pages: 275
      order: 1
      base_file: 96C2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
